#!/bin/bash -l

#SBATCH -A eboss
#SBATCH -q premium
#SBATCH -N 1
#SBATCH -L SCRATCH,project
#SBATCH -C haswell
#SBATCH -J grid_multipoles
#SBATCH -t 00:00:00

#OpenMP settings:
export OMP_NUM_THREADS=64
export OMP_PLACES=threads
export OMP_PROC_BIND=true


filepath='/global/cscratch1/sd/grazi/useful_mocks/EZmocks'
outputpath='output'
file_name='QSO_rand_full.dat'
output_name='ezmock_ran.dat'

../grid_multipoles -in $filepath/$file_name -box 3500 -nside 80 -scale 1 > $outputpath/$output_name

